[package]
name = "todo_list"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
jsonwebtoken = "9.3.0"
bcrypt = "0.16.0"
actix-web = "4"
actix-web-httpauth = "0.8.2"